name: 'CodeLogic .Net Agent'
description: 'Scans .Net artifacts into your '


inputs:
  codelogic_host:
    description: 'The host address of the CodeLogic instance without the "/codelogic/ui/" part.'
    required: true
  agent_uuid:
    description: 'The UUID of the Agent in CodeLogic.'
    required: true
  agent_password:
    description: 'The password for the agent.'
    required: true
  application_name:
    description: 'The Application node to create that will be the parent of all objects found in the scan.'
    required: true
  scan_space:
    description: 'The name of the scan space that the data will be saved to. If specified, a ScanSpace with this name will be created if not found. If not specified, information will be saved to the default ScanSpace.'
    required: false
  scan_path:
    description: 'The path of the file and folder to scan. Must start with /github/workspace/'
    default: "/github/workspace"
    required: false
  scan_path_depth:
    description: 'During scanning, this value will be used as the depth of subdirectories to traverse before stopping.'
    default: '500'
    required: false
  recursive_filter:
    description: 'Filters scanning to only those filenames that contain the given string.'
    required: false
  exclusion_filter:
    description: 'Excludes directories and filenames that contain the given string from being scanned.'
    required: false
  reference_path:
    description: 'Path to recursively search for assembly references.'
    required: false
  method_filter:
    description: 'A substring of namespace prefixes that should be included in method-invokes-method relationships.'
    required: false
  database_identities:
    description: 'A database identity to use in the creation of relationships.'
    required: false
  show_compiler_generated:
    description: 'Will not show compiler generated code in resulting graph.'
    default: 'false'
    required: false
  force_rescan:
    description: 'Forces the agent to rescan already scanned artifacts.'
    default: 'false'
    required: false
  expunge_scan_sessions:
    description: 'Instruct the server to delete all other scan sessions created by this agent and its configuration after the current scan session has completed successfully.'
    default: 'false'
    required: false


runs:
  using: 'docker'
  image: docker://public.ecr.aws/codelogic.com/codelogic_dotnet:latest
  args: [
    "analyze",
    "-p=${{ inputs.scan_path }}",
    "-a=${{ inputs.application_name }}",
    "--depth=${{ inputs.scan_path_depth }}",
    "${{ inputs.scan_space != null && format('-s={0}', inputs.scan_space) || null }}",
    "${{ inputs.recursive_filter != null && format('-f={0}', inputs.recursive_filter) || null }}",
    "${{ inputs.exclusion_filter != null && format('-x={0}', inputs.exclusion_filter) || null }}",
    "${{ inputs.reference_path != null && format('--ref-path {0}', inputs.reference_path) || null }}",
    "${{ inputs.method_filter != null && format('-m={0}', inputs.method_filter) || null }}",
    "${{ inputs.database_identities != null && format('-d={0}', inputs.database_identities) || null }}",
    "${{ inputs.show_compiler_generated == 'true' && '--show-compiler-generated' || null }}",
    "${{ inputs.force_rescan == 'true' && '--rescan' || null }}",
    "${{ inputs.expunge_scan_sessions == 'true' && '-e' || null }}"
  ]
  env:
    CODELOGIC_HOST: ${{ inputs.codelogic_host }}
    AGENT_UUID: ${{ inputs.agent_uuid }}
    AGENT_PASSWORD: ${{ inputs.agent_password }}

